### ISSUE TITLE
yaml and lexc tests not working

### ISSUE THREAD

**Issue by xoyito** [giellalt/lang-kek#4]

**Comment by Trondtr** [comment]
I compile and run "make check", and the tests that are set up to run do run, cf. the files: ls test/src/morphology/*.sh
test/src/morphology/generate-adjective-lemmas.sh  test/src/morphology/generate-propernoun-lemmas.sh test/src/morphology/tag_test.sh
test/src/morphology/generate-noun-lemmas.sh       test/src/morphology/generate-verb-lemmas.sh

You probably will not ahve too much use of these tests, since they are not set up with the correct tags. As a matter of fact, the file src/fst/stems/nouns.lexc does not include any tags. for the nouns. 

The yaml tests do not work since you did not set up any tests. 

Come to think of it, your issue message may refer to a warning at the end of the compilation process. If my guess is correct, you may safely ignore it: The alert comes if you have not set up the tools to run yaml tests (there is documentation on how to do it), but since lang-kek does not contain any yaml and lexc you should start worrying about the alert only after having written some tests .

**Comment by xoyito** [comment]
jolom yaml test passing
